CLASS zbp_r_cs04_customer DEFINITION
  PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZR_CS04_Customer.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_r_cs04_customer IMPLEMENTATION.
ENDCLASS.
